<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">

<meta name="Author" content="Cream Software">
<meta name="Generator" content="Pajak V6 (6.1.1.0)">

<!-- nazwa strony pomocy -->
<title>Program settings - Dynamic hints in scripts</title>

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha512-MoRNloxbStBcD8z3M/2BmnT+rg4IsMxPkXaGh2zD6LGNNFE80W3onsAhRcMAMrSoyWL9xD7Ert0men7vR8LUZg==" crossorigin="anonymous">

<link rel="stylesheet" href="style.css" type="text/css">
</head>
<body>

<!-- topmenu start -->
<? include "include/topmenu.html"; ?>
<!-- topmenu end -->

<div class="container-fluid">

<!-- google search start -->
<? include "include/googlesearch.html"; ?>
<!-- google search end -->

<!-- tabelka z trescia -->
<table>
<tr>
<td>

<!-- nag&#322;owek g&#322;owny tematu -->
<h1>Program settings - Dynamic hints in scripts</h1>



<!-- tre&#347;&#263; pomocy -->
<p>This group of settings allows you to define how the dynamic hint function works for scripting languages. In this window, there are several groups of settings responsible for the various functions of the tooltip.</p><h2>Dynamic JavaScript hints</h2>

<p>This group of settings includes toggles that allow you to specify the content presented in dynamic hints for the JavaScript language. Check the options that should be considered when creating the list. You can define, for example, whether the list of functions available for dynamic hints will include functions declared in script files attached to the document, or specify the display of global elements.</p><h2>Dynamic JavaScript help</h2>

<p>This group will help you determine the content of the dynamic balloon help displayed for JavaScript language elements.</p><h2>Other options</h2>

<p><b>Display only methods and properties compatible with ...</b><br></p><p>This option allows you to determine the compliance of the displayed hints with the selected JavaScript language specification. Not all browsers support all specifications, so using these options you can narrow down the displayed hints only to the elements that interest you.</p><p><b>By default in ASP use</b><br></p><p>This option allows you to specify your preferred language when writing ASP programs. As a result, the dynamic hints that will be displayed will only apply to the language you are using. You can choose either JavaScript or VBScript.</p><h2>User Constructions in the OK button menu</h2>




<!-- tre&#347;&#263; pomocy -->
<p>This category of settings allows you to define special constructs that are used when inserting the code generated by the tag editor tools. This allows you to define your own type of tag code insertion, e.g. for scripting languages. User constructs will be placed in the menu of the OK button in the tool boxes that allow you to insert tags. Constructions can be added and modified using the buttons next to the list.</p><p>The creation of a construction consists in entering the text inside which the symbol will be located (a letter preceded by a percent sign, e.g. <tt>%s /tt&gt; ), which when inserting the code into the document using this construction will be converted into the code of the tag generated by tool. For example, you can create your own construct like <tt> sprintf ("%s ) </tt> . If you use it in the cross reference tool, you will cause the link tag code to be inserted as follows:</tt></p>
<pre>sprintf("&amp;lt;a href=\"www.creamsoft.com\" target=\"_blank\"&amp;gt;creamsoft website&amp;lt;/a&amp;gt;");</pre>



<p>There are four symbols with the following meanings:</p><ul>
        <li><tt>%settings</tt> - tag code will be inserted in formatting according to program settings</li>
        <li><tt>%h</tt> - Tag code in lowercase HTML formatting will be inserted</li>
        <li><tt>%Html</tt> - the tag code in HTML formatting, in uppercase, will be inserted</li>
        <li><tt>%xhtml</tt> - XHTML tag code will be inserted</li>
</ul>If, on the other hand, you want to use a percent sign in your construction, insert it with the <tt>%%</tt> symbol.<h2>Definition file editor for scripting languages</h2>

<p>By using the button in this group you will enable the <a href="tagdata_editor_tdf_scripts.php"> script definition editor </a> tool, which allows you to create definitions for new script language elements as well as modify the definitions of already defined script elements.</p></td>
</tr>
</table>

<table>
<tr>
<td width="100%" class="tbrelatedtopics">
<!-- pokrewne tematy -->
<h4>Related topics</h4>
<ul>
	<li><a href="settings_codeinsight.php#settingslistcodeinsight">Other facilitation settings</a></li><li><a href="main_editor_codeinsight.php">Dynamic code</a></li><li><a href="coding_scripts_jsvb.php">Using scripts in Spider</a></li><li><a href="tagdata_editor_tdf_scripts.php">Definition file editor for scripts</a></li></ul>
</td>
</tr>
</table>
<!-- pokrewne tematy koniec-->
<p class="prawa"><a href="#top">To top</a></p>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js" integrity="sha512-/DXTXr6nQodMUiq+IUJYCt2PPOUjrHJ9wFrqpJ3XkgPNOZVfMok7cRw6CSxyCQxXn6ozlESsSh1/sMCTF1rL/g==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/js/bootstrap.bundle.min.js" integrity="sha512-kBFfSXuTKZcABVouRYGnUo35KKa1FBrYgwG4PAx7Z2Heroknm0ca2Fm2TosdrrI356EDHMW383S3ISrwKcVPUw==" crossorigin="anonymous"></script>
</div><!-- container end -->

<!-- Cookie Banner -->
<? include "include/cookiebanner.html"; ?>
<!-- End of Cookie Banner -->

<!-- Google analytics -->
<? include "include/analytics.html"; ?>
<!-- End of Google analytics -->

</body>
</html>
